# Generated by Django 4.2.7 on 2025-04-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('PATIENT_LIST', 'Patient List'), ('APPOINTMENT_STATS', 'Appointment Statistics'), ('BILLING_SUMMARY', 'Billing Summary'), ('PRESCRIPTION_ANALYSIS', 'Prescription Analysis'), ('CUSTOM', 'Custom Report')], max_length=50),
        ),
    ]
